// this is the code we used for static data before , which is now not useful as we adding roles and permission dynamically
// kept only for backward compatibility — new permissions are fetched from DB dynamically
export const PERMISSIONS = {
    VIEW_USERS: "VIEW_USERS",
    CREATE_USERS: "CREATE_USERS",
    UPDATE_USERS: "UPDATE_USERS",
    DELETE_USERS: "DELETE_USERS",
    DOWNLOAD_USERS: "DOWNLOAD_USERS",

    VIEW_GUEST_USERS: "VIEW_GUEST_USERS",
    CREATE_GUEST_USERS: "CREATE_GUEST_USERS",
    UPDATE_GUEST_USERS: "UPDATE_GUEST_USERS",
    DELETE_GUEST_USERS: "DELETE_GUEST_USERS",
    DOWNLOAD_GUEST_USERS: "DOWNLOAD_GUEST_USERS",

    VIEW_DASHBOARD: "VIEW_DASHBOARD",

    VIEW_KITCHENS: "VIEW_KITCHENS",
    CREATE_KITCHENS: "CREATE_KITCHENS",
    UPDATE_KITCHENS: "UPDATE_KITCHENS",
    DELETE_KITCHENS: "DELETE_KITCHENS",
    DOWNLOAD_KITCHENS: "DOWNLOAD_KITCHENS",

    VIEW_MENUS: "VIEW_MENUS",
    CREATE_MENUS: "CREATE_MENUS",
    UPDATE_MENUS: "UPDATE_MENUS",
    DELETE_MENUS: "DELETE_MENUS",
    DOWNLOAD_MENUS: "DOWNLOAD_MENUS",

    VIEW_ORDERS: "VIEW_ORDERS",
    CREATE_ORDERS: "CREATE_ORDERS",
    UPDATE_ORDERS: "UPDATE_ORDERS",
    DELETE_ORDERS: "DELETE_ORDERS",
    DOWNLOAD_ORDERS: "DOWNLOAD_ORDERS",

    VIEW_REPORTS: "VIEW_REPORTS",
    CREATE_REPORTS: "CREATE_REPORTS",
    UPDATE_REPORTS: "UPDATE_REPORTS",
    DELETE_REPORTS: "DELETE_REPORTS",
    DOWNLOAD_REPORTS: "DOWNLOAD_REPORTS",

    VIEW_PAYMENTS: "VIEW_PAYMENTS",
    CREATE_PAYMENTS: "CREATE_PAYMENTS",
    UPDATE_PAYMENTS: "UPDATE_PAYMENTS",
    DELETE_PAYMENTS: "DELETE_PAYMENTS",
    DOWNLOAD_PAYMENTS: "DOWNLOAD_PAYMENTS",

    VIEW_INVENTORY: "VIEW_INVENTORY",
    CREATE_INVENTORY: "CREATE_INVENTORY",
    UPDATE_INVENTORY: "UPDATE_INVENTORY",
    DELETE_INVENTORY: "DELETE_INVENTORY",
    DOWNLOAD_INVENTORY: "DOWNLOAD_INVENTORY",

    VIEW_CATEGORIES: "VIEW_CATEGORIES",
    CREATE_CATEGORIES: "CREATE_CATEGORIES",
    UPDATE_CATEGORIES: "UPDATE_CATEGORIES",
    DELETE_CATEGORIES: "DELETE_CATEGORIES",
    DOWNLOAD_CATEGORIES: "DOWNLOAD_CATEGORIES",


    VIEW_SETTINGS: "VIEW_SETTINGS",
    CREATE_SETTINGS: "CREATE_SETTINGS",
    DELETE_SETTINGS: "DELETE_SETTINGS",
    UPDATE_SETTINGS: "UPDATE_SETTINGS",
    DOWNLOAD_SETTINGS: "DOWNLOAD_SETTINGS",


    VIEW_PROMOTIONS: "VIEW_PROMOTIONS",
    CREATE_PROMOTIONS: "CREATE_PROMOTIONS",
    UPDATE_PROMOTIONS: "UPDATE_PROMOTIONS",
    DELETE_PROMOTIONS: "DELETE_PROMOTIONS",
    DOWNLOAD_PROMOTIONS: "DOWNLOAD_PROMOTIONS",

    VIEW_SUPPORTS: "VIEW_SUPPORTS",
    CREATE_SUPPORTS: "CREATE_SUPPORTS",
    UPDATE_SUPPORTS: "UPDATE_SUPPORTS",
    DELETE_SUPPORTS: "DELETE_SUPPORTS",
    DOWNLOAD_SUPPORTS: "DOWNLOAD_SUPPORTS",

    VIEW_ROLES: "VIEW_ROLES",
    CREATE_ROLES: "CREATE_ROLES",
    UPDATE_ROLES: "UPDATE_ROLES",
    DELETE_ROLES: "DELETE_ROLES",
    DOWNLOAD_ROLES: "DOWNLOAD_ROLES",

    VIEW_MESSAGES: "VIEW_MESSAGES",
    DELETE_MESSAGES: "DELETE_MESSAGES",

    VIEW_SUPPLIERS: "VIEW_SUPPLIERS",
    CREATE_SUPPLIERS: "CREATE_SUPPLIERS",
    UPDATE_SUPPLIERS: "UPDATE_SUPPLIERS",
    DELETE_SUPPLIERS: "DELETE_SUPPLIERS",
    DOWNLOAD_SUPPLIERS: "DOWNLOAD_SUPPLIERS",
} as const;
