// this is the code we used for static data before , which is now not useful as we adding roles and permission dynamically
// kept only for backward compatibility — new roles/permissions are fetched from DB dynamically
import { ROLES } from "./roles";
import { PERMISSIONS } from "./permissions";

export type Role = (typeof ROLES)[keyof typeof ROLES];
export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const adminPermissions: Permission[] = [
    // View
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_GUEST_USERS,
    PERMISSIONS.VIEW_KITCHENS,
    PERMISSIONS.VIEW_MENUS,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_PAYMENTS,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.VIEW_CATEGORIES,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.VIEW_PROMOTIONS,
    PERMISSIONS.VIEW_SUPPORTS,
    PERMISSIONS.VIEW_ROLES,

    // Create
    PERMISSIONS.CREATE_USERS,
    PERMISSIONS.CREATE_GUEST_USERS,
    PERMISSIONS.CREATE_KITCHENS,
    PERMISSIONS.CREATE_MENUS,
    PERMISSIONS.CREATE_ORDERS,
    PERMISSIONS.CREATE_REPORTS,
    PERMISSIONS.CREATE_PAYMENTS,
    PERMISSIONS.CREATE_INVENTORY,
    PERMISSIONS.CREATE_CATEGORIES,
    PERMISSIONS.CREATE_SETTINGS,
    PERMISSIONS.CREATE_PROMOTIONS,
    PERMISSIONS.CREATE_SUPPORTS,
    PERMISSIONS.CREATE_ROLES,

    // Update
    PERMISSIONS.UPDATE_USERS,
    PERMISSIONS.UPDATE_GUEST_USERS,
    PERMISSIONS.UPDATE_KITCHENS,
    PERMISSIONS.UPDATE_MENUS,
    PERMISSIONS.UPDATE_ORDERS,
    PERMISSIONS.UPDATE_REPORTS,
    PERMISSIONS.UPDATE_PAYMENTS,
    PERMISSIONS.UPDATE_INVENTORY,
    PERMISSIONS.UPDATE_CATEGORIES,
    PERMISSIONS.UPDATE_SETTINGS,
    PERMISSIONS.UPDATE_PROMOTIONS,
    PERMISSIONS.UPDATE_SUPPORTS,
    PERMISSIONS.UPDATE_ROLES,

    // Delete
    PERMISSIONS.DELETE_USERS,
    PERMISSIONS.DELETE_GUEST_USERS,
    PERMISSIONS.DELETE_KITCHENS,
    PERMISSIONS.DELETE_MENUS,
    PERMISSIONS.DELETE_ORDERS,
    PERMISSIONS.DELETE_REPORTS,
    PERMISSIONS.DELETE_PAYMENTS,
    PERMISSIONS.DELETE_INVENTORY,
    PERMISSIONS.DELETE_CATEGORIES,
    PERMISSIONS.DELETE_SETTINGS,
    PERMISSIONS.DELETE_PROMOTIONS,
    PERMISSIONS.DELETE_SUPPORTS,
    PERMISSIONS.DELETE_ROLES,

    // Download
    PERMISSIONS.DOWNLOAD_USERS,
    PERMISSIONS.DOWNLOAD_GUEST_USERS,
    PERMISSIONS.DOWNLOAD_KITCHENS,
    PERMISSIONS.DOWNLOAD_MENUS,
    PERMISSIONS.DOWNLOAD_ORDERS,
    PERMISSIONS.DOWNLOAD_REPORTS,
    PERMISSIONS.DOWNLOAD_PAYMENTS,
    PERMISSIONS.DOWNLOAD_INVENTORY,
    PERMISSIONS.DOWNLOAD_CATEGORIES,
    PERMISSIONS.DOWNLOAD_SETTINGS,
    PERMISSIONS.DOWNLOAD_PROMOTIONS,
    PERMISSIONS.DOWNLOAD_SUPPORTS,
    PERMISSIONS.DOWNLOAD_ROLES,

    // Messages
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.DELETE_MESSAGES,

    // Suppliers
    PERMISSIONS.VIEW_SUPPLIERS,
    PERMISSIONS.CREATE_SUPPLIERS,
    PERMISSIONS.UPDATE_SUPPLIERS,
    PERMISSIONS.DELETE_SUPPLIERS,
    PERMISSIONS.DOWNLOAD_SUPPLIERS,
];

export const rolePermissions: Record<Role, Permission[]> = {
    [ROLES.SUPER_ADMIN]: adminPermissions,

    [ROLES.ADMIN]: adminPermissions,

    [ROLES.STAFF]: [
        PERMISSIONS.VIEW_DASHBOARD,
        PERMISSIONS.VIEW_PAYMENTS,
        PERMISSIONS.VIEW_MENUS,
        PERMISSIONS.VIEW_INVENTORY,
    ],

    [ROLES.KITCHEN_MANAGER]: [
        PERMISSIONS.VIEW_DASHBOARD,
        PERMISSIONS.VIEW_MENUS,
        PERMISSIONS.CREATE_MENUS,
        PERMISSIONS.UPDATE_MENUS,

        PERMISSIONS.VIEW_ORDERS,
        PERMISSIONS.UPDATE_ORDERS,

        PERMISSIONS.VIEW_KITCHENS,

        PERMISSIONS.VIEW_CATEGORIES,
        PERMISSIONS.UPDATE_CATEGORIES,

        PERMISSIONS.VIEW_INVENTORY,
        PERMISSIONS.UPDATE_INVENTORY,
    ],

    [ROLES.PAYMENT_MANAGER]: [
        PERMISSIONS.VIEW_DASHBOARD,
        PERMISSIONS.VIEW_PAYMENTS,
        PERMISSIONS.CREATE_PAYMENTS,
        PERMISSIONS.UPDATE_PAYMENTS,

        PERMISSIONS.VIEW_REPORTS,
        PERMISSIONS.DOWNLOAD_REPORTS,
    ],

    [ROLES.SUPPORT_STAFF]: [
        PERMISSIONS.VIEW_DASHBOARD,
        PERMISSIONS.VIEW_SUPPORTS,
        PERMISSIONS.CREATE_SUPPORTS,
        PERMISSIONS.UPDATE_SUPPORTS,
    ],

    [ROLES.CUSTOMER]: [],
};

export function hasPermission(
    role: Role,
    permission: Permission,
): boolean {
    return rolePermissions[role]?.includes(permission) ?? false;
}
